permalink: /:categories/:title.html
url: "http://pasindud.github.io/jekyll-masonry/"
full_name: "Clobot-Hurdler"
first_name: "Clobot"
last_name: "Hurdler"
blog_title: "Blog title "
author_img_name_path: "/images/users/user.jpg"
disqus_shortname: "pasinduland"
copyright_year: "2019"
google_analytics_code: ""
aboutme: "Something about the author here"
twitter: "Ghosteyes1"
github: "pasindud"
facebook: "mepasindu"
linkined_url: ""
blog_logo: "/images/blog/clobothurdler.png"
