permalink: /:categories/:title.html
url: ""
full_name: "Clobot-Hurdler"
first_name: "Clobot"
last_name: "Hurdler"
blog_title: "Blog title "
author_img_name_path: "/images/users/user.jpg"
disqus_shortname: "clobot-hurdler-github-io"
copyright_year: "2019"
google_analytics_code: ""
aboutme: "Something about the author here"
twitter: ""
github: ""
facebook: ""
linkined_url: ""
blog_logo: "/images/blog/clobothurdler.png"
